sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 8
branches:
  only:
    - master
script:
  - npm run validate
after_success:
  - npm run coverage
  - npm run release
